name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}
      DOCKER_ORG: hsnbd
      SERVICE_PREFIX: kube-mailer
      
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

     # Step 3: Build all images first
    - name: Build all Docker images
      run: |
        SERVICES=("mail-ui" "primary-server" "decorator-server" "worker")
        for SERVICE in "${SERVICES[@]}"; do
          echo "Building $SERVICE..."
          docker build ./services/$SERVICE \
            --file ./services/$SERVICE/Dockerfile \
            --tag $DOCKER_ORG/$SERVICE_PREFIX-$SERVICE:latest \
            --tag $DOCKER_ORG/$SERVICE_PREFIX-$SERVICE:${IMAGE_TAG}
        done

    # Step 4: Verify built images
    - name: List built images
      run: docker images | grep kube-mailer

    # Step 5: Push all images one by one
    - name: Push all Docker images
      run: |
        SERVICES=("mail-ui" "primary-server" "decorator-server" "worker")
        for SERVICE in "${SERVICES[@]}"; do
          echo "Pushing $SERVICE..."
          docker push $DOCKER_ORG/$SERVICE_PREFIX-$SERVICE:latest
          docker push $DOCKER_ORG/$SERVICE_PREFIX-$SERVICE:${IMAGE_TAG}
        done